#ifndef SHELL_INTERACTIVE_GLOBAL_H
#define SHELL_INTERACTIVE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SHELL_INTERACTIVE_LIBRARY)
#  define SHELL_INTERACTIVE_EXPORT Q_DECL_EXPORT
#else
#  define SHELL_INTERACTIVE_EXPORT Q_DECL_IMPORT
#endif

#endif // SHELL_INTERACTIVE_GLOBAL_H
